site_name: DICOM4QI
site_description: DICOM for Quantitative Imaging (DICOM4QI)
site_author: QIICR

repo_url: https://github.com/qiicr/dicom4qi
repo_name: dicom4qi

docs_dir: docs

theme:
  name: material
  #name: readthedocs
  #custom_dir: custom_theme

pages:
  - Introduction: index.md
  - Scope: scope.md
  - Participants: participants.md
  - Instructions for participants:
      - Overview: instructions.md
      - Segmentation: instructions/seg.md
      - Measurements (DICOM SR TID1500): instructions/sr-tid1500.md
      - Parametric maps: instructions/pm.md
  #    - Longitudinal annotation: instructions/longitudinal.md
      - Tractography (DICOM TR): instructions/tr.md
  #    - Results organization: results/index.md
  - Results - Segmentation:
      - Summary: results/seg/index.md
      - 3D Slicer: results/seg/3dslicer.md
      - ePAD: results/seg/epad.md
      - Brainlab: results/seg/brainlab.md
      - AIM on ClearCanvas: results/seg/aimclearcanvas.md
      - Siemens syngo.via: results/seg/syngovia.md
      - MeVisLab: results/seg/mevislab.md
      - MITK: results/seg/mitk.md
      - Mint: results/seg/mint.md
      - AMI: results/seg/ami.md
      - Pixelmed: results/seg/pixelmed.md
      - dcmjs+cornerstone: results/seg/dcmjs+cornerstone.md
      - FreeSurfer: results/seg/freesurfer.md
  - Results - Measurements (DICOM SR TID1500):
      - Summary: results/sr-tid1500/index.md
      - ePAD: results/sr-tid1500/epad.md
      - 3D Slicer: results/sr-tid1500/3dslicer.md
  - Results - Parametric maps:
      - Summary: results/pm/index.md
      - MeVisLab: results/pm/mevislab.md
      - 3D Slicer: results/pm/slicer.md
      - OsiriX: results/pm/osirix.md
      - ePAD: results/pm/epad.md
      - vtk-dicom: results/pm/vtk-dicom.md
      - Cornerstone: results/pm/cornerstone.md
  - Results - Tractography:
      - Summary: results/tr/index.md
      - 3D Slicer: results/tr/slicer.md
      - Brainlab: results/tr/brainlab.md
      - MITK: results/tr/mitk.md
      - Prism: results/tr/prism.md
  - Resources:
      - Open source tools: resources/software.md
      - Public datasets: resources/datasets.md
  - History: history.md
  - Acknowledgments: acks.md
  - Referencs: refs.md

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

google_analytics: ['UA-44852938-11', 'dicom4qi.readthedocs.io']
