site_name: DICOM4QI
site_description: DICOM for Quantitative Imaging (DICOM4QI)
site_author: QIICR

repo_url: https://github.com/qiicr/dicom4qi
repo_name: dicom4qi

docs_dir: content

theme:
  name: readthedocs
  #name: material
  #custom_dir: custom_theme

pages:
  - Introduction: index.md
  - Scope: scope.md
  - Participants: participants.md
  - Instructions for participants:
      - General instructions: instructions/instructions.md
      - Segmentations: instructions/seg.md
      - Measurements (DICOM SR TID1500): instructions/sr-tid1500.md
      - Parametric maps: instructions/pm.md
      - Longitudinal annotation: instructions/longitudinal.md
      - Tractography (DICOM TR): instructions/tr.md
  - Results:
      - Organization: results/index.md
      - Segmentation: results/seg/index.md
  - History: history.md
  - Referencs: refs.md

markdown_extensions:
    - toc:
        permalink: 
